#!/bin/bash


curl -LO https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img

cloud-localds seed.img user-data.yaml metadata.yaml

qemu-system-x86_64 \
	-machine accel=kvm,type=q35 \
	-cpu host \
	-m 2G \
	-nographic \
	-device virtio-net-pci,netdev=net0 \
	-netdev user,id=net0,hostfwd=tcp::2222-:22 \
	-drive if=virtio,format=qcow2,file=focal-server-cloudimg-amd64.img \
	-drive if=virtio,format=raw,file=seed.img
