#cloud-config
manage_etc_hosts: true
users:
  - name: user 
    groups: sudo
    sudo: ALL=(ALL) 
    ssh_import_id:
      - gh:JZiegener
package_upgrade: true
packages:
  - bmon 
  - bwm-ng 
  - curl 
  - htop 
  - iftop 
  - iotop 
  - libpam-systemd 
  - locales-all 
  - locate 
  - nano 
  - net-tools 
  - ntpdate 
  - nfs-common 
  - qemu-guest-agent 
  - rsync 
  - screen 
  - strace 
  - sysstat 
  - snmpd 
  - sudo 
  - tcpdump 
  - tmux 
  - vlan 
  - vnstat
runcmd:
  - apt purge snapd -y
  - apt autoremove -y
  - apt autoclean -y
  
